### ISSUE TITLE
Should stream-producer default SENZING_INPUT_URL to the truthset?

### ISSUE THREAD

**Issue by ryanbasile** [Senzing/stream-producer#182]
**Is your feature request related to a problem? Please describe.**
Our CloudFormations default to https://s3.amazonaws.com/public-read-access/TestDataSets/SenzingTruthSet/truth-set-3.0.0.jsonl, the stream-producer docker-compose defaults to https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json

**Describe the solution you'd like**
Should our stream-producer docker-compose also default to https://s3.amazonaws.com/public-read-access/TestDataSets/SenzingTruthSet/truth-set-3.0.0.jsonl?

**Comment by docktermj** [comment]
@jbutcher21 Let's you and I get together to figure out what to add to the TruthSet to make it more "versatile".

For instance:

We should add some records in the TruthSet to trigger redoer.

**Comment by docktermj** [comment]
Fixed via https://github.com/Senzing/docker-compose-demo/issues/298
