### ISSUE TITLE
Exception when running as container and printing help

### ISSUE THREAD

**Issue by antaenc** [Senzing/stream-producer#98]
Running with docker as per the example in the readme results in an exception after printing the help information.

`--> sudo docker run \
>   --interactive \
>   --rm \
>   --tty \
>   senzing/stream-producer
usage: stream-producer.py [-h]
                          {avro-to-azure-queue,avro-to-kafka,avro-to-rabbitmq,avro-to-sqs,avro-to-sqs-batch,avro-to-stdout,csv-to-azure-queue,csv-to-kafka,csv-to-rabbitmq,csv-to-sqs,csv-to-sqs-batch,csv-to-stdout,gzipped-json-to-azure-queue,gzipped-json-to-kafka,gzipped-json-to-rabbitmq,gzipped-json-to-sqs,gzipped-json-to-sqs-batch,gzipped-json-to-stdout,json-to-azure-queue,json-to-kafka,json-to-rabbitmq,json-to-sqs,json-to-sqs-batch,json-to-stdout,parquet-to-azure-queue,parquet-to-kafka,parquet-to-rabbitmq,parquet-to-sqs,parquet-to-sqs-batch,parquet-to-stdout,sleep,version,docker-acceptance-test}
                          ...

Queue messages. For more information, see https://github.com/Senzing/stream-
producer

positional arguments:
  {avro-to-azure-queue,avro-to-kafka,avro-to-rabbitmq,avro-to-sqs,avro-to-sqs-batch,avro-to-stdout,csv-to-azure-queue,csv-to-kafka,csv-to-rabbitmq,csv-to-sqs,csv-to-sqs-batch,csv-to-stdout,gzipped-json-to-azure-queue,gzipped-json-to-kafka,gzipped-json-to-rabbitmq,gzipped-json-to-sqs,gzipped-json-to-sqs-batch,gzipped-json-to-stdout,json-to-azure-queue,json-to-kafka,json-to-rabbitmq,json-to-sqs,json-to-sqs-batch,json-to-stdout,parquet-to-azure-queue,parquet-to-kafka,parquet-to-rabbitmq,parquet-to-sqs,parquet-to-sqs-batch,parquet-to-stdout,sleep,version,docker-acceptance-test}
                        Subcommands (SENZING_SUBCOMMAND):
    avro-to-azure-queue
                        Read Avro file and send to Azure Queue.
    avro-to-kafka       Read Avro file and send to Kafka.
    avro-to-rabbitmq    Read Avro file and send to RabbitMQ.
    avro-to-sqs         Read Avro file and print to AWS SQS.
    avro-to-sqs-batch   Read Avro file and print to AWS SQS using batch.
                        DEPRECATED: Use avro-to-sqs and set
                        SENZING_RECORDS_PER_MESSAGE
    avro-to-stdout      Read Avro file and print to STDOUT.
    csv-to-azure-queue  Read CSV file and send to Azure Queue.
    csv-to-kafka        Read CSV file and send to Kafka.
    csv-to-rabbitmq     Read CSV file and send to RabbitMQ.
    csv-to-sqs          Read CSV file and print to SQS.
    csv-to-sqs-batch    Read CSV file and print to SQS using batch.
                        DEPRECATED: Use csv-to-sqs and set
                        SENZING_RECORDS_PER_MESSAGE
    csv-to-stdout       Read CSV file and print to STDOUT.
    gzipped-json-to-azure-queue
                        Read gzipped JSON file and send to Azure Queue.
    gzipped-json-to-kafka
                        Read gzipped JSON file and send to Kafka.
    gzipped-json-to-rabbitmq
                        Read gzipped JSON file and send to RabbitMQ.
    gzipped-json-to-sqs
                        Read gzipped JSON file and send to AWS SQS.
    gzipped-json-to-sqs-batch
                        Read gzipped JSON file and send to AWS SQS using
                        batch. DEPRECATED: Use gzipped-json-to-sqs and set
                        SENZING_RECORDS_PER_MESSAGE
    gzipped-json-to-stdout
                        Read gzipped JSON file and print to STDOUT.
    json-to-azure-queue
                        Read JSON file and send to Azure Queue.
    json-to-kafka       Read JSON file and send to Kafka.
    json-to-rabbitmq    Read JSON file and send to RabbitMQ.
    json-to-sqs         Read JSON file and send to AWS SQS.
    json-to-sqs-batch   Read JSON file and send to AWS SQS using batch.
                        DEPRECATED: Use json-to-sqs and set
                        SENZING_RECORDS_PER_MESSAGE
    json-to-stdout      Read JSON file and print to STDOUT.
    parquet-to-azure-queue
                        Read Parquet file and send to Azure Queue.
    parquet-to-kafka    Read Parquet file and send to Kafka.
    parquet-to-rabbitmq
                        Read Parquet file and send to RabbitMQ.
    parquet-to-sqs      Read Parquet file and print to AWS SQS.
    parquet-to-sqs-batch
                        Read Parquet file and print to AWS SQS using batch.
                        DEPRECATED: Use parquet-to-sqs and set
                        SENZING_RECORDS_PER_MESSAGE
    parquet-to-stdout   Read Parquet file and print to STDOUT.
    sleep               Do nothing but sleep. For Docker testing.
    version             Print version of program.
    docker-acceptance-test
                        For Docker acceptance testing.

optional arguments:
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "/app/stream-producer.py", line 2795, in <module>
    do_sleep(args)
  File "/app/stream-producer.py", line 2712, in do_sleep
    config = get_configuration(args)
  File "/app/stream-producer.py", line 712, in get_configuration
    new_key = key.format(subcommand.replace('-', '_'))
AttributeError: 'NoneType' object has no attribute 'replace'

`

**Comment by docktermj** [comment]
Pull request:

- https://github.com/Senzing/stream-producer/pull/101
